[subject]
name = "Example_Subject"

[input]
mask_dir = 'z:\Labmembers\Ingvild\RM1\microglia_ramification_model\analysis_test\ramification_minus_soma'
pattern = "*.tif*"

[output]
out_dir = 'C:\Users\SmartBrain_32C_TR\Documents\GitHub\standard_test_data\lsfm_cell_mapping\build_signal_points'

[space]
name = "subject_space"
orientation = "las"
resolution_um = [1.8, 1.8, 20.0]

[processing]
slice_start = 1
one_based = true
max_workers = 8
show_progress = true
progress_interval = 25
